apiVersion: apps/v1
kind: Deployment
metadata:
  name: sundayfunapp-deployment-pvc
  labels:
    app: sundayfunapp-pvc
spec:
  selector:
    matchLabels:
      app: sundayfunapp-pvc
  template:
    metadata:
      labels:
        app: sundayfunapp-pvc
    spec:
      volumes:
      - name: sundayfun-storage
        persistentVolumeClaim:
          claimName: sundayfun-pvc
      containers:
      - name: sundayfunapp-pvc
        image: debasisdas1976/sundayfunapp
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: sundayfun-storage
