apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        ports:
        - containerPort: 3306    
        image: registry.access.redhat.com/rhscl/mysql-57-rhel7:5.7-47
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: review-secret
              key: user
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: review-secret
              key: database
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: review-secret
              key: password
              
